apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3  # Number of desired replicas (pods) to run
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest  # Use the latest Nginx image from Docker Hub
          ports:
            - containerPort: 80  # Expose port 80 from the Nginx container
